language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer update --prefer-source
script: return 1
notifications:
  email:
    - frank@francoisfaubert.com
